project_id = "sahpxaadldarejtkirmk"

[functions.health]
verify_jwt = false

[functions.routes-service]
verify_jwt = false

[functions.trips-service]
verify_jwt = false

[functions.bookings-service]
verify_jwt = false

[functions.payments-service]
verify_jwt = false

[functions.notifications-service]
verify_jwt = false

[functions.vendors-service]
verify_jwt = false

[functions.ussd]
verify_jwt = false

[functions.admin-service]
verify_jwt = false

[functions.seed-users]
verify_jwt = false
