// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sahpxaadldarejtkirmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhaHB4YWFkbGRhcmVqdGtpcm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NDQ1NzgsImV4cCI6MjA4ODEyMDU3OH0.l0j5KJohVL6WrsZyErZG-aH9FuzV3QiPsTniU0wXo-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});